### PR TITLE
Add support for tox 3

### PR DESCRIPTION
**Pull request by dcrosta**
Also closes #5

### CODE REVIEW

**Comment by dcrosta** [comment]
Choosing to ignore travis build failures on 3.7dev, will care when 3.7 lands for real

**Comment by pjdelport** [comment]
Can we have a new release for this fix?

**Comment by dcrosta** [comment]
CC @kbalonek ^

**Comment by pjdelport** [comment]
Thanks! :)

**Comment by dcrosta** [comment]
Happy to help, and glad people are actually using it!

**Pull request merged**
